manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim
    - name: frap129
      url-base: https://github.com/frap129
  projects:
    - name: zmk
      remote: frap129
      revision: main
      import: app/west.yml
  self:
    path: config
